{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs2-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.frontendHost }}
        - {{ .Values.ingress.apiHost }}
        - {{ .Values.monitoring.ingress.grafanaHost }}
        - {{ .Values.monitoring.ingress.prometheusHost }}
        - {{ .Values.monitoring.ingress.alertsHost }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cs2-frontend-service
                port:
                  number: 80
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cs2-api-service
                port:
                  number: {{ .Values.api.service.port }}
    - host: {{ .Values.monitoring.ingress.grafanaHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.monitoring.ingress.grafanaService.name }}
                port:
                  number: {{ .Values.monitoring.ingress.grafanaService.port }}
    - host: {{ .Values.monitoring.ingress.prometheusHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.monitoring.ingress.prometheusService.name }}
                port:
                  number: {{ .Values.monitoring.ingress.prometheusService.port }}
    - host: {{ .Values.monitoring.ingress.alertsHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.monitoring.ingress.alertmanagerService.name }}
                port:
                  number: {{ .Values.monitoring.ingress.alertmanagerService.port }}
{{- end }}
