apiVersion: batch/v1
kind: CronJob
metadata:
  name: cs2-scraper
spec:
  schedule: {{ .Values.scraper.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.scraper.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.scraper.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: {{ .Values.scraper.activeDeadlineSeconds }}
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          containers:
            - name: scraper
              image: "{{ .Values.scraper.image.repository }}:{{ .Values.scraper.image.tag }}"
              imagePullPolicy: {{ .Values.global.imagePullPolicy }}
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: ["ALL"]
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
              resources:
                {{- toYaml .Values.scraper.resources | nindent 16 }}
              env:
                - name: PYTHONDONTWRITEBYTECODE
                  value: "1"
                - name: DB_HOST
                  value: cs2-db-service
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: cs2-config
                      key: POSTGRES_DB
                - name: DB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: cs2-config
                      key: POSTGRES_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cs2-secret
                      key: POSTGRES_PASSWORD
                - name: MARKET_ITEMS
                  valueFrom:
                    configMapKeyRef:
                      name: cs2-config
                      key: MARKET_ITEMS
          volumes:
            - name: tmp
              emptyDir: {}
          restartPolicy: Never
